if (speed player < 60) then {
	"SmokeShellGreen" createVehicle (position player);
	sleep .1;
	"SmokeShellGreen" createVehicle (position player);
	sleep .1;
	"SmokeShellGreen" createVehicle (position player);
	sleep .1;
	"SmokeShellGreen" createVehicle (position player);
	sleep .1;
	"SmokeShellGreen" createVehicle (position player);
	sleep .1;
	"SmokeShellGreen" createVehicle (position player);
	sleep .1;
	"SmokeShellGreen" createVehicle (position player);
	sleep .1;
	"SmokeShellGreen" createVehicle (position player);
	sleep .1;
	"SmokeShellGreen" createVehicle (position player);
	sleep .1;
	"SmokeShellGreen" createVehicle (position player);
	sleep .1;
};